title: Jakov Gotovac Borčić
# logo: ![20230505_122347 (1)](https://github.com/JakovGotovacBorcic/Internship_Portfolio/assets/150671291/37ffeccc-6e79-4e41-8ccb-1cc7bbb06bf8)
description: Resume
show_downloads: false
theme: jekyll-theme-minimal
